import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useIntersection } from 'react-use'
import { useRef, useState } from 'react'
import ScrollToContent from '../components/Landing/ScrollToContent'
import QuestionMark from '../components/Icon/QuestionMark'
import VisibilitySensor from 'react-visibility-sensor'
import PolicyWheel from '../components/Landing/PolicyWheel'
import CountUp from 'react-countup'
import RiseImpactLogo from '/public/image/logo/rise-impact.svg'

const intersectopnOptions = {
  root: null,
  rootMargin: '0px',
  threshold: 1,
}
const Home: NextPage = () => {
  const learnmoreRef = useRef(null)
  const [hasView, setHasView] = useState<boolean>(false)
  const intersection = useIntersection(learnmoreRef, intersectopnOptions)

  return (
    <div className="relative">
      <Head>
        <title>Policy Dialogue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-fixed fixed w-1/2 h-auto overflow-hidden sm:w-[52%] sm:h-[120%] bg-right bg-[#232151] mix-blend-screen bg-opacity-75 from-[#191919] to-[#232151] rounded-l-[50%] bg-gradient-to-b bottom-0 -top-24 right-0"></div>

      <main className="relative">
        <section
          className={`${
            intersection && intersection.intersectionRatio < 1 ? '' : 'blur-md backdrop-blur-md saturate-50 backdrop-saturate-50'
          } grid h-[90vh] overflow-hidden bg-fixed bg-center landing-bg-size filter bg-no-repeat transition backdrop-filter place-content-center bg-hero-pattern-mobile sm:bg-hero-pattern`}
        >
          <div className="pt-24 space-y-8 text-center text-white">
            <h1 className="text-5xl sm:text-7xl">Policy Dialogue</h1>
            <h2 className="text-xl">
              โพลิซี ไดอะล็อก
              <br />
              กระบวนการหารือเชิงนโยบาย
            </h2>
          </div>
        </section>

        <section className="relative h-full bg-white">
          <ScrollToContent />
          <div ref={learnmoreRef} className="grid grid-cols-1 gap-6 pt-32 sm:grid-cols-2" id="learnmore">
            <div className="flex flex-col col-span-1 px-6 pt-16 space-y-4 sm:px-24 text-body">
              <h2 className="text-4xl font-semibold leading-snug sm:text-5xl ">
                นโยบายที่ดี สังคมต้อง
                <br />
                ร่วมกันออกแบบ
              </h2>
              <p className="sm:text-lg">
                สร้างการมีส่วนร่วมที่เปิดกว้าง เปิดใจรับฟังความ แตกต่าง ให้ผู้คนได้แลกเปลี่ยนความคิดเห็นบนฐานความรู้และประสบการณ์ เพื่อร่วมออกแบบนโยบาย ให้เป็น
                ‘นโยบาย’ ของคนในสังคมอย่างแท้จริง
              </p>
            </div>
            <div className="relative col-span-1">
              <Image src="https://via.placeholder.com/1024x640" loading="lazy" height="640" width="1024" className="w-full" alt="about-policy-dialogue" />
            </div>
          </div>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <div className="col-span-1 bg-pink-50">circle element</div>
            <div className="flex flex-col col-span-1 px-6 py-16 space-y-4 sm:px-24 text-body">
              <h2 className="text-4xl font-semibold leading-snug sm:text-5xl">
                เพราะนโยบาย
                <br />
                เกี่ยวข้องกับทุกมิติใน
                <br />
                ชีวิตของผู้คน
              </h2>
              <p className="sm:text-lg">
                เราจะมีชีวิตที่ดีขึ้นได้ ก็ต้องอาศัยนโยบายสาธารณะ ที่ตอบโจทย์ สอดคล้องกับบริบท พร้อมรองรับ ความเปลี่ยนแปลงและความต้องการของสังคม
              </p>
            </div>
          </div>
          <div className="hidden grid-cols-4 gap-6 mt-6 sm:grid bg-purple-50">
            <div className="w-full h-64 text-center">footer circle element</div>
          </div>
        </section>

        <section className="relative h-full bg-secondary">
          <div className="px-12 py-12 space-y-12 text-white sm:py-24">
            <h2 className="text-4xl text-center sm:text-5xl">นโยบายเพื่อสังคมสูงวัย</h2>
            <div className="grid grid-cols-1 gap-6 text-center md:grid-cols-5">
              <blockquote className="bg-[#36723b] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">แก่ตัวไปจะมีใครดูแลไหม?</p>
              </blockquote>
              <blockquote className="bg-[#cc79a7] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">ถ้าทำงานไม่ไหว จะมีกินมีใช้ หรือเปล่า?</p>
              </blockquote>
              <blockquote className="bg-[#36723b] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">รัฐจะดูแลเราอย่างไร ตอนเราอายุ 70 ปี?</p>
              </blockquote>
              <blockquote className="bg-[#6badcb] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">ถ้าต้องอยู่ บ้านพักคนชรา จะจ่ายไหวไหม?</p>
              </blockquote>
              <blockquote className="bg-[#daa13d] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">หากเจ็บป่วยขึ้นมาใครจะพา ไปส่ง โรงพยาบาล?</p>
              </blockquote>
            </div>
          </div>
        </section>
        <section className="relative h-full bg-[#242054]">
          <div className="flex flex-col items-center justify-center px-6 py-20 text-white">
            <QuestionMark className="w-48 h-48" />
            <p className="text-lg text-center max-w-prose ">
              คำถามเหล่านี้ เป็นหนึ่งในโจทย์สำคัญของการพัฒนานโยบาย เพื่อสร้างการเปลี่ยนแปลงเชิงระบบ กระบวนการหาคำตอบ จึงไม่ได้มีเพียงฝั่งผู้กำหนดนโยบาย
              แต่ยังมีเสียงจากผู้ปฏิบัติงานที่เกี่ยวข้อง ภาครัฐ ภาคประชาสังคม ภาคเอกชน และประชาชน ที่ล้วนเป็นผู้รับผลกระทบไม่ทางตรงก็ทางอ้อม
            </p>
          </div>
          <div className="absolute bottom-0 -ml-4 triangle-up left-1/2"></div>
        </section>
        <section className="relative h-full overflow-hidden bg-secondary">
          <div className="absolute top-0 right-0 translate-y-[50%] w-[344px] h-1/2 bg-[#232151] mix-blend-screen bg-opacity-75 from-[#191919] to-[#232151] rounded-tl-full rounded-bl-full bg-gradient-to-b"></div>
          <div className="absolute top-0 right-0 w-full h-full bg-fixed bg-center bg-no-repeat filter blur-md bg-step bg-step-blur-pattern"></div>
          <div className="absolute top-0 w-full h-full bg-fixed bg-no-repeat bg-top-16 bg-step-pattern bg-step"></div>
          <div className="absolute w-full bg-no-repeat h-[40rem] -top-16 -bg-top-6 bg-contain bg-process-step">
            <div className="flex justify-center">
              <div className="flex flex-col items-center justify-center pt-10 space-y-6 font-bold text-center bg-white rounded-full w-80 h-80 text-body">
                <h3 className="text-2xl">
                  ตอบคำถามดังกล่าว
                  <br /> ผ่านกรอบการทำงาน
                  <br />
                </h3>

                <span className="text-4xl">5 ขั้น</span>
              </div>
            </div>
          </div>
          <div className="relative w-full flex justify-center mt-[32rem]">
            <Link href="/process">
              <a className="w-3/4 sm:w-max btn">กระบวนการของเรา</a>
            </Link>
          </div>
          <div className="relative flex flex-col items-center justify-center h-full p-6 mx-6 my-12 bg-white sm:p-12 sm:mx-24 rounded-xl">
            <div className="flex flex-col py-12 space-y-4 jutify-center">
              <h2 className="text-4xl text-center text-body">TGRI x RISE IMPACT</h2>
              <p className="text-center sm:text-lg text-body max-w-prose">
                มูลนิธิสถาบันวิจัยและพัฒนาผู้สูงอายุไทย (มส.ผส.) และ ไรซ์ อิมแพค ได้ร่วมกันออกแบบกระบวนการ พัฒนานโยบายเพื่อรองรับสังคมผู้สูงวัย โดยครอบคลุม 7
                ประเด็นหลัก
              </p>
            </div>

            <div className="relative">
              {/* <div className="absolute mx-auto mt-56 -ml-28 inset-x-1/2 ">
                <div className="flex items-center justify-center w-56 h-56 p-6 rounded-full bg-[#FEEDEA]">
                  <h3 className="text-2xl text-center text-body">นโยบายเพื่อสังคมสูงวัย</h3>
                </div>
              </div> */}
              <PolicyWheel className="fill-current text-primary" />
            </div>
          </div>
        </section>
        <section className="relative h-full py-24 bg-white">
          <VisibilitySensor partialVisibility active={!hasView} onChange={(isVisible) => setHasView(isVisible)}>
            {({ isVisible }) => (
              <div className="grid grid-cols-1 gap-6 px-6 sm:px-24 sm:max-w-3/4 sm:grid-cols-2">
                <div className="flex flex-col col-span-1 space-y-8 text-body">
                  <h2 className="text-4xl font-semibold leading-snug sm:text-5xl ">
                    สร้างการมีส่วนร่วม
                    <br /> เพื่อออกแบบนโยบาย
                    <br /> ในระยะเวลา 1 ปี
                  </h2>
                  <div className="hidden sm:block">
                    <Link href="/value">
                      <a className="btn">คุณค่ากระบวนการ</a>
                    </Link>
                  </div>
                </div>
                <div className="grid grid-cols-1 col-span-1 gap-8 sm:grid-cols-2">
                  <div className="flex flex-col col-span-1 space-y-4 text-body">
                    <p className="text-base">จัดวงหารือแบบออฟไลน์และออนไลน์</p>
                    <p className="text-6xl">
                      {isVisible ? <CountUp end={30} duration={2} /> : '0'}
                      <span className="text-base"> ครั้ง</span>
                    </p>
                  </div>
                  <div className="flex flex-col col-span-1 space-y-4 text-body">
                    <p className="text-base">มีผู้เข้าร่วมที่หลากหลายมากกว่า</p>
                    <p className="text-6xl">
                      {isVisible ? <CountUp end={400} duration={2.5} /> : '0'}
                      <span className="text-base"> ครั้ง</span>
                    </p>
                  </div>
                  <div className="flex flex-col col-span-1 space-y-4 text-body">
                    <p className="text-base">เกิด public engagement ผ่านช่องทางออนไลน์</p>
                    <p className="text-6xl">
                      {isVisible ? <CountUp end={2} duration={2} /> : '0'}
                      <span className="text-base"> ครั้ง</span>
                    </p>
                  </div>
                  <div className="flex flex-col col-span-1 space-y-4 text-body">
                    <p className="text-base">มีผู้เข้าร่วมที่หลากหลายมากกว่า</p>
                    <p className="text-6xl">
                      {isVisible ? <CountUp end={1000} duration={2.75} separator="," /> : '0'}
                      <span className="text-base"> ครั้ง</span>
                    </p>
                  </div>
                </div>
                <div className="flex justify-center mt-12 sm:hidden">
                  <Link href="/value">
                    <a className="w-3/4 btn">คุณค่ากระบวนการ</a>
                  </Link>
                </div>
              </div>
            )}
          </VisibilitySensor>
        </section>
        <section className="relative h-full py-24 bg-top bg-no-repeat bg-cover bg-secondary bg-landing-footer">
          <div className="flex flex-col items-center justify-center space-y-6">
            <h3 className="text-4xl leading-snug text-center text-white sm:text-5xl">
              โพลิซี ไดอะล็อก
              <br /> ทำงานอย่างไร ?
            </h3>
            <p className="text-base text-center text-white sm:text-lg max-w-prose">
              เราได้จัดทำคู่มือการจัดกระบวนการจากประสบการณ์ของทีมงาน ผู้ที่สนใจสามารถนำไปปรับใช้สำหรับออกแบบและพัฒนานโยบาย ทุกระดับ ทุกประเด็นในสังคม
              เพื่อร่วมกันสร้างการเปลี่ยนแปลงเชิงระบบ
            </p>
            <div className="flex justify-center pt-6">
              <Link href="/">
                <a className="w-3/4 btn sm:w-max">ดาวน์โหลดคู่มือฉบับเต็ม</a>
              </Link>
            </div>
            <div className="flex justify-center w-3/4 pt-6">
              <div className="flex items-center justify-between w-full px-24 py-6 bg-white bg-top bg-no-repeat bg-contain rounded-lg bg-rise-impact-footer">
                <div>
                  <Image src={RiseImpactLogo} alt="rise-impact-logo" className="w-full h-full" width="240" height="120" />
                </div>
                <div>
                  <Link href="/about">
                    <a className="w-3/4 btn sm:w-max">เกี่ยวกับเรา</a>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <footer>Footer here</footer>
    </div>
  )
}

export default Home
