import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useIntersection } from 'react-use'
import { useRef, useState } from 'react'
import ScrollToContent from '../components/Landing/ScrollToContent'
import QuestionMark from '../components/Icon/QuestionMark'
import VisibilitySensor from 'react-visibility-sensor'
import PolicyWheel from '../components/Landing/PolicyWheel'
import CountUp from 'react-countup'

const intersectopnOptions = {
  root: null,
  rootMargin: '0px',
  threshold: 1,
}
const Home: NextPage = () => {
  const learnmoreRef = useRef(null)
  const [hasView, setHasView] = useState<boolean>(false)
  const intersection = useIntersection(learnmoreRef, intersectopnOptions)

  return (
    <div className="relative">
      <Head>
        <title>Policy Dialogue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-fixed fixed w-[52%] h-[120%] bg-right bg-[#232151] mix-blend-screen bg-opacity-75 from-[#191919] to-[#232151] rounded-tl-[120%] rounded-bl-[100%] bg-gradient-to-b bottom-0 -top-24 right-0"></div>
      <main className="relative">
        <section
          className={`${
            intersection && intersection.intersectionRatio < 1 ? '' : 'blur-md backdrop-blur-md saturate-50 backdrop-saturate-50'
          } z-10 grid h-[90vh] overflow-hidden bg-fixed bg-center landing-bg-size filter bg-no-repeat transition backdrop-filter place-content-center bg-hero-pattern`}
        >
          <div className="pt-24 space-y-8 text-center text-white">
            <h1 className="text-5xl sm:text-7xl">Policy Dialogue</h1>
            <h2 className="text-xl">
              โพลิซี ไดอะล็อก
              <br />
              กระบวนการหารือเชิงนโยบาย
            </h2>
          </div>
        </section>

        <section className="relative h-full bg-white">
          <ScrollToContent />
          <div ref={learnmoreRef} className="grid grid-cols-1 gap-6 pt-32 sm:grid-cols-2" id="learnmore">
            <div className="flex flex-col col-span-1 px-24 pt-16 space-y-2 text-body">
              <h2 className="text-5xl font-semibold leading-snug ">
                นโยบายที่ดี สังคมต้อง
                <br />
                ร่วมกันออกแบบ
              </h2>
              <p className="text-sm sm:text-lg">
                สร้างการมีส่วนร่วมที่เปิดกว้าง เปิดใจรับฟังความ แตกต่าง ให้ผู้คนได้แลกเปลี่ยนความคิดเห็นบนฐานความรู้และประสบการณ์ เพื่อร่วมออกแบบนโยบาย ให้เป็น
                ‘นโยบาย’ ของคนในสังคมอย่างแท้จริง
              </p>
            </div>
            <div className="relative col-span-1">
              <Image src="https://via.placeholder.com/1024x640" loading="lazy" height="640" width="1024" className="w-full" alt="about-policy-dialogue" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-6">
            <div className="col-span-1 bg-pink-50">circle element</div>
            <div className="flex flex-col col-span-1 px-24 pt-16 space-y-2 text-body">
              <h2 className="text-5xl font-semibold leading-snug">
                เพราะนโยบาย
                <br />
                เกี่ยวข้องกับทุกมิติใน
                <br />
                ชีวิตของผู้คน
              </h2>
              <p className="text-sm sm:text-lg">
                เราจะมีชีวิตที่ดีขึ้นได้ ก็ต้องอาศัยนโยบายสาธารณะ ที่ตอบโจทย์ สอดคล้องกับบริบท พร้อมรองรับ ความเปลี่ยนแปลงและความต้องการของสังคม
              </p>
            </div>
          </div>
          <div className="grid grid-cols-4 gap-6 mt-6 bg-purple-50">
            <div className="w-full h-64 text-center">footer circle element</div>
          </div>
          blabla
        </section>

        <section className="relative h-full bg-secondary">
          <div className="px-12 py-24 space-y-12 text-white">
            <h2 className="text-5xl text-center">นโยบายเพื่อสังคมสูงวัย</h2>
            <div className="grid grid-cols-5 gap-6 text-center">
              <blockquote className="bg-[#36723b] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">แก่ตัวไปจะมีใครดูแลไหม?</p>
              </blockquote>
              <blockquote className="bg-[#cc79a7] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">ถ้าทำงานไม่ไหว จะมีกินมีใช้ หรือเปล่า?</p>
              </blockquote>
              <blockquote className="bg-[#36723b] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">รัฐจะดูแลเราอย่างไร ตอนเราอายุ 70 ปี?</p>
              </blockquote>
              <blockquote className="bg-[#6badcb] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">ถ้าต้องอยู่ บ้านพักคนชรา จะจ่ายไหวไหม?</p>
              </blockquote>
              <blockquote className="bg-[#daa13d] p-6 w-full h-64 flex items-center justify-center">
                <p className="text-xl">หากเจ็บป่วยขึ้นมาใครจะพา ไปส่ง โรงพยาบาล?</p>
              </blockquote>
            </div>
          </div>
        </section>
        <section className="relative h-full bg-[#242054]">
          <div className="flex flex-col items-center justify-center px-12 py-20 text-white">
            <QuestionMark className="w-48 h-48" />
            <p className="text-lg text-center max-w-prose ">
              คำถามเหล่านี้ เป็นหนึ่งในโจทย์สำคัญของการพัฒนานโยบาย เพื่อสร้างการเปลี่ยนแปลงเชิงระบบ กระบวนการหาคำตอบ จึงไม่ได้มีเพียงฝั่งผู้กำหนดนโยบาย
              แต่ยังมีเสียงจากผู้ปฏิบัติงานที่เกี่ยวข้อง ภาครัฐ ภาคประชาสังคม ภาคเอกชน และประชาชน ที่ล้วนเป็นผู้รับผลกระทบไม่ทางตรงก็ทางอ้อม
            </p>
          </div>
        </section>
        <section className="relative h-full overflow-hidden bg-secondary">
          <div className="absolute right-0 translate-y-[50%] w-[344px] h-1/2 bg-[#232151] mix-blend-screen bg-opacity-75 from-[#191919] to-[#232151] rounded-tl-full rounded-bl-full bg-gradient-to-b"></div>
          <div className="absolute top-0 right-0 w-full h-full bg-fixed bg-center bg-no-repeat filter blur-md bg-step bg-step-blur-pattern"></div>
          <div className="absolute top-0 w-full h-full bg-fixed bg-no-repeat bg-top-24 bg-step-pattern bg-step"></div>
          <div className="absolute w-full p-20 bg-top bg-no-repeat -top-28 bg-survey bg-process-step">
            <div className="flex justify-center">
              <div className="flex flex-col items-center justify-center pt-8 space-y-4 font-bold text-center bg-white rounded-full w-72 h-72 text-body">
                <h3 className="text-2xl">
                  ตอบคำถามดังกล่าว
                  <br /> ผ่านกรอบการทำงาน
                  <br />
                </h3>

                <span className="text-4xl">5 ขั้น</span>
              </div>
            </div>
          </div>
          <div className="relative flex justify-center mt-96">
            <Link href="/process">
              <a className="btn">กระบวนการของเรา</a>
            </Link>
          </div>
          <div className="relative flex flex-col items-center justify-center h-full p-12 mx-24 my-12 bg-white rounded-xl">
            <div className="flex flex-col py-12 space-y-4 jutify-center">
              <h2 className="text-4xl text-center text-body">TGRI X RISE IMPACT</h2>
              <p className="text-lg text-center text-body max-w-prose">
                มูลนิธิสถาบันวิจัยและพัฒนาผู้สูงอายุไทย (มส.ผส.) และ ไรซ์ อิมแพค ได้ร่วมกันออกแบบกระบวนการ พัฒนานโยบายเพื่อรองรับสังคมผู้สูงวัย โดยครอบคลุม 7
                ประเด็นหลัก
              </p>
            </div>

            <div className="relative">
              <div className="absolute mx-auto mt-56 -ml-28 inset-x-1/2 ">
                <div className="flex items-center justify-center w-56 h-56 p-6 rounded-full bg-[#FEEDEA]">
                  <h3 className="text-2xl text-center text-body">นโยบายเพื่อสังคมสูงวัย</h3>
                </div>
              </div>
              <PolicyWheel className="fill-current text-primary" />
            </div>
          </div>
        </section>
        <section className="relative h-full py-24 bg-white">
          <VisibilitySensor partialVisibility active={!hasView} onChange={(isVisible) => setHasView(isVisible)}>
            {({ isVisible }) => (
              <div className="grid grid-cols-2 gap-6 px-24">
                <div className="flex flex-col col-span-1 px-24 space-y-8 text-body">
                  <h2 className="text-5xl font-semibold leading-snug ">
                    สร้างการมีส่วนร่วม
                    <br /> เพื่อออกแบบนโยบาย
                    <br /> ในระยะเวลา 1 ปี
                  </h2>
                  <div>
                    <Link href="/value">
                      <a className="btn">คุณค่ากระบวนการ</a>
                    </Link>
                  </div>
                </div>
                <div className="grid grid-cols-2 col-span-1 gap-8">
                  <div className="flex flex-col space-y-4 text-body">
                    <p className="text-base">จัดวงหารือแบบออฟ ไลน์และออนไลน์</p>
                    <p className="text-6xl">
                      {isVisible ? <CountUp end={30} duration={2} /> : '0'}
                      <span className="text-base"> ครั้ง</span>
                    </p>
                  </div>
                  <div className="flex flex-col space-y-4 text-body">
                    <p className="text-base">มีผู้เข้าร่วมที่ หลากหลายมากกว่า</p>
                    <p className="text-6xl">
                      {isVisible ? <CountUp end={400} duration={2.5} /> : '0'}
                      <span className="text-base"> ครั้ง</span>
                    </p>
                  </div>
                  <div className="flex flex-col space-y-4 text-body">
                    <p className="text-base">เกิด public engagement ผ่านช่องทางออนไลน์</p>
                    <p className="text-6xl">
                      {isVisible ? <CountUp end={2} duration={2} /> : '0'}
                      <span className="text-base"> ครั้ง</span>
                    </p>
                  </div>
                  <div className="flex flex-col space-y-4 text-body">
                    <p className="text-base">มีผู้เข้าร่วมที่ หลากหลายมากกว่า</p>
                    <p className="text-6xl">
                      {isVisible ? <CountUp end={1000} duration={2.75} separator="," /> : '0'}
                      <span className="text-base"> ครั้ง</span>
                    </p>
                  </div>
                </div>
              </div>
            )}
          </VisibilitySensor>
        </section>
      </main>

      <footer>Footer here</footer>
    </div>
  )
}

export default Home
