import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ArrowDownIcon } from '@heroicons/react/solid'
import { useIntersection } from 'react-use'
import { useRef } from 'react'
import ScrollToContent from '../components/Landing/ScrollToContent'
import QuestionMark from '../components/Icon/QuestionMark'

const intersectopnOptions = {
  root: null,
  rootMargin: '0px',
  threshold: 1,
}
const Home: NextPage = () => {
  const learnmoreRef = useRef(null)
  const intersection = useIntersection(learnmoreRef, intersectopnOptions)

  return (
    <div className="relative">
      <Head>
        <title>Policy Dialogue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-fixed fixed object-right-top w-1/2 h-[120%] bg-[#232151] mix-blend-screen bg-opacity-75 from-[#191919] to-[#232151] rounded-l-[50%] bg-gradient-to-b -top-24 right-0"></div>
      <main className="relative">
        <section
          className={`${
            intersection && intersection.intersectionRatio < 1 ? '' : 'blur-md backdrop-blur-md saturate-50 backdrop-saturate-50'
          } z-10 grid h-screen p-6 overflow-hidden bg-fixed bg-top filter bg-no-repeat bg-cover transition backdrop-filter place-content-center bg-hero-pattern`}
        >
          <div className="space-y-6 text-center text-white">
            <h1 className="text-5xl sm:text-7xl">Policy Dialogue</h1>
            <h2 className="text-2xl">
              โพลิซี ไดอะล็อก
              <br />
              กระบวนการหารือเชิงนโยบาย
            </h2>
          </div>
        </section>

        <section className="relative h-full bg-white -mt-36">
          <ScrollToContent />
          <div ref={learnmoreRef} className="grid grid-cols-1 gap-6 pt-32 sm:grid-cols-2" id="learnmore">
            <div className="flex flex-col col-span-1 px-24 pt-16 space-y-2 text-body">
              <h2 className="text-5xl font-semibold leading-snug ">
                นโยบายที่ดี สังคมต้อง
                <br />
                ร่วมกันออกแบบ
              </h2>
              <p className="text-sm sm:text-lg">
                สร้างการมีส่วนร่วมที่เปิดกว้าง เปิดใจรับฟังความ แตกต่าง ให้ผู้คนได้แลกเปลี่ยนความคิดเห็นบนฐานความรู้และประสบการณ์ เพื่อร่วมออกแบบนโยบาย ให้เป็น
                ‘นโยบาย’ ของคนในสังคมอย่างแท้จริง
              </p>
            </div>
            <div className="relative col-span-1">
              <Image src="https://via.placeholder.com/1024x640" loading="lazy" height="640" width="1024" className="w-full" alt="about-policy-dialogue" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-6">
            <div className="col-span-1 bg-pink-50">circle element</div>
            <div className="flex flex-col col-span-1 px-24 pt-16 space-y-2 text-body">
              <h2 className="text-5xl font-semibold leading-snug">
                เพราะนโยบาย
                <br />
                เกี่ยวข้องกับทุกมิติใน
                <br />
                ชีวิตของผู้คน
              </h2>
              <p className="text-sm sm:text-lg">
                เราจะมีชีวิตที่ดีขึ้นได้ ก็ต้องอาศัยนโยบายสาธารณะ ที่ตอบโจทย์ สอดคล้องกับบริบท พร้อมรองรับ ความเปลี่ยนแปลงและความต้องการของสังคม
              </p>
            </div>
          </div>
          <div className="grid grid-cols-4 gap-6 mt-6 bg-purple-50">
            <div className="w-full h-64 text-center">footer circle element</div>
          </div>
          blabla
        </section>

        <section className="relative h-full bg-secondary">
          <div className="px-12 py-24 space-y-12 text-white">
            <h2 className="text-5xl text-center">นโยบายเพื่อสังคมสูงวัย</h2>
            <div className="grid grid-cols-5 gap-6">
              <div className="bg-[#36723b] w-full h-64 flex items-center justify-center">
                <p className="text-xl">แก่ตัวไปจะมีใครดูแลไหม?</p>
              </div>
              <div className="bg-[#cc79a7] w-full h-64 flex items-center justify-center">
                <p className="text-xl">ถ้าทำงานไม่ไหว จะมีกินมีใช้ หรือเปล่า?</p>
              </div>
              <div className="bg-[#36723b] w-full h-64 flex items-center justify-center">
                <p className="text-xl">รัฐจะดูแลเราอย่างไร ตอนเราอายุ 70 ปี?</p>
              </div>
              <div className="bg-[#6badcb] w-full h-64 flex items-center justify-center">
                <p className="text-xl">ถ้าต้องอยู่ บ้านพักคนชรา จะจ่ายไหวไหม?</p>
              </div>
              <div className="bg-[#daa13d] w-full h-64 flex items-center justify-center">
                <p className="text-xl">หากเจ็บป่วยขึ้นมาใครจะพา ไปส่ง โรงพยาบาล?</p>
              </div>
            </div>
          </div>
        </section>
        <section className="relative h-full bg-[#242054]">
          <div className="flex flex-col items-center justify-center px-12 py-24 text-white">
            <QuestionMark className="w-48 h-48" />
            <p className="text-lg text-center max-w-prose ">
              คำถามเหล่านี้ เป็นหนึ่งในโจทย์สำคัญของการพัฒนานโยบาย เพื่อสร้างการเปลี่ยนแปลงเชิงระบบ กระบวนการหาคำตอบ จึงไม่ได้มีเพียงฝั่งผู้กำหนดนโยบาย
              แต่ยังมีเสียงจากผู้ปฏิบัติงานที่เกี่ยวข้อง ภาครัฐ ภาคประชาสังคม ภาคเอกชน และประชาชน ที่ล้วนเป็นผู้รับผลกระทบไม่ทางตรงก็ทางอ้อม
            </p>
          </div>
        </section>
        <section className="relative h-full bg-secondary">ตอบคำถามดังกล่าว ผ่านกรอบการทำงาน 5 ขั้น</section>
        <div>
          <a href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
